use_frameworks!

platform :ios, '10.0'

target 'MultipleLineChartView_Example' do
  pod 'MultipleLineChartView', :path => '../'

  target 'MultipleLineChartView_Tests' do
    inherit! :search_paths

    
  end
end
